# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mass Mesh
email: info@massmesh.org
description: > # this means to ignore newlines until "baseurl:"
  As the ISP cartel consolidates power, we're forging a movement of resistance.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://massmesh.org" # the base hostname & protocol for your site
github_username:  MassMesh

# Build settings
markdown: kramdown
keep_files: [wiki, support, blog, analytics]

